name=PopetLCD
version=1.0.0
author=Popet
maintainer=Popet
sentence=Lightweight HD44780 driver for AVR 
paragraph=Direct port access, about 370~ bytes of flash for hello world.
category=Display
url=https://github.com/popetik/PopetLCD
architectures=avr
